# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6

# Command to install system dependencies
before_install:
  - sudo apt-get install libxmlsec1-dev pkg-config

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis codecov

# Command to run tests, e.g. python setup.py test
script: tox
