# -*- coding: utf-8 -*-

# 8.7. Monedas

CURRENCIES = {
    "AED": u"United Arab Emi",
    "AFA": u"Afghanistan, Af",
    "AUD": u"Australia, Doll",
    "AWG": u"Aruba, Guilders",
    "AZM": u"Azerbaijan, Man",
    "BAM": u"Bosnia and Herz",
    "BBD": u"Barbados, Dolla",
    "BDT": u"Bangladesh, Tak",
    "BGN": u"Bulgaria, Leva",
    "BHD": u"Bahrain, Dinars",
    "BIF": u"Burundi, Francs",
    "BMD": u"Bermuda, Dollar",
    "BND": u"Brunei Darussal",
    "BOB": u"Bolivia, Bolivi",
    "BRL": u"Brazil, Brazil",
    "BSD": u"Bahamas, Dollar",
    "BTN": u"Bhutan, Ngultru",
    "BWP": u"Botswana, Pulas",
    "BYR": u"Belarus, Rubles",
    "BZD": u"Belize, Dollars",
    "CAD": u"Canada, Dollars",
    "CDF": u"Congo/Kinshasa",
    "CHF": u"Switzerland, Fr",
    "CLP": u"Chile, Pesos",
    "CNY": u"China, Yuan Ren",
    "COP": u"Colombia, Pesos",
    "CRC": u"Costa Rica, Col",
    "CUP": u"Cuba, Pesos",
    "CVE": u"Cape Verde, Esc",
    "CYP": u"Cyprus, Pounds",
    "CZK": u"Czech Republic",
    "DJF": u"Djibouti, Franc",
    "DKK": u"Denmark, Kroner",
    "DOP": u"Dominican Repub",
    "DZD": u"Algeria, Algeri",
    "EEK": u"Estonia, Krooni",
    "EGP": u"Egypt, Pounds",
    "ERN": u"Eritrea, Nakfa",
    "ETB": u"Ethiopia, Birr",
    "FJD": u"Fiji, Dollars",
    "FKP": u"Falkland Island",
    "GBP": u"United Kingdom",
    "GEL": u"Georgia, Lari",
    "GGP": u"Guernsey, Pound",
    "GHC": u"Ghana, Cedis",
    "GIP": u"Gibraltar, Poun",
    "GMD": u"Gambia, Dalasi",
    "GNF": u"Guinea, Francs",
    "GTQ": u"Guatemala, Quet",
    "GYD": u"Guyana, Dollars",
    "HKD": u"Hong Kong, Doll",
    "HNL": u"Honduras, Lempi",
    "HRK": u"Croatia, Kuna",
    "HTG": u"Haiti, Gourdes",
    "HUF": u"Hungary, Forint",
    "IDR": u"Indonesia, Rupi",
    "ILS": u"Israel, New She",
    "IMP": u"Isle of Man, Po",
    "INR": u"India, Rupees",
    "IQD": u"Iraq, Dinars",
    "IRR": u"Iran, Rials",
    "ISK": u"Iceland, Kronur",
    "JMD": u"Jamaica, Dollar",
    "JOD": u"Jordan, Dinars",
    "JPY": u"Japan, Yen",
    "KES": u"Kenya, Shilling",
    "KGS": u"Kyrgyzstan, Som",
    "KHR": u"Cambodia, Riels",
    "KMF": u"Comoros, Francs",
    "KPW": u"Korea (North)",
    "KRW": u"Korea (South)",
    "KWD": u"Kuwait, Dinars",
    "KYD": u"Cayman Islands,",
    "KZT": u"Kazakstan, Teng",
    "LAK": u"Laos, Kips",
    "LBP": u"Lebanon, Pounds",
    "LKR": u"Sri Lanka, Rupe",
    "MGA": u"Madagascar, Ari",
    "MKD": u"Macedonia, Dena",
    "MMK": u"Myanmar (Burma)",
    "MNT": u"Mongolia, Tugri",
    "MOP": u"Macau, Patacas",
    "MRO": u"Mauritania, Oug",
    "MTL": u"Malta, Liri",
    "MUR": u"Mauritius, Rupe",
    "MVR": u"Maldives (Maldi",
    "MWK": u"Malawi, Kwachas",
    "MXN": u"Mexico, Pesos",
    "MYR": u"Malaysia, Ringg",
    "MZM": u"Mozambique, Met",
    "NAD": u"Namibia, Dollar",
    "NGN": u"Nigeria, Nairas",
    "NIO": u"Nicaragua, Gold",
    "NOK": u"Norway, Krone",
    "NPR": u"Nepal, Nepal Ru",
    "NZD": u"New Zealand, Do",
    "OMR": u"Oman, Rials",
    "PAB": u"Panama, Balboa",
    "PEN": u"Peru, Nuevos So",
    "PGK": u"Papua New Guine",
    "PHP": u"Philippines, Pe",
    "PKR": u"Pakistan, Rupee",
    "PLN": u"Poland, Zlotych",
    "PYG": u"Paraguay, Guara",
    "QAR": u"Qatar, Rials",
    "ROL": u"Romania, Lei",
    "RSD": u"Serbia, Dinars",
    "RUB": u"Russia Rubles",
    "RWF": u"Rwanda, Rwanda",
    "SAR": u"Saudi Arabia, R",
    "SBD": u"Solomon Islands",
    "SCR": u"Seychelles, Rup",
    "SDD": u"Sudan, Dinars",
    "SDG": u"Sudan, Pounds",
    "SEK": u"Sweden, Kronor",
    "SGD": u"Singapore, Doll",
    "SHP": u"Saint Helena, P",
    "SIT": u"Slovenia, Tolar",
    "SKK": u"Slovakia, Korun",
    "SLL": u"Sierra Leone, L",
    "SOS": u"Somalia, Shilli",
    "SRD": u"Suriname, Dolla",
    "STD": u"Sao Tome and P",
    "SVC": u"El Salvador, Co",
    "SYP": u"Syria, Pounds",
    "SZL": u"Swaziland, Emal",
    "THB": u"Thailand, Baht",
    "TJS": u"Tajik., Somo.",
    "TMT": u"Turkmenistan, M",
    "TND": u"Tunisia, Dinars",
    "TOP": u"Tonga, Paanga",
    "TRY": u"Turkey, Liras",
    "TTD": u"Trinidad and To",
    "TVD": u"Tuvalu, Tuvalu",
    "TWD": u"Taiwan, New Dol",
    "TZS": u"Tanzania, Shill",
    "UAH": u"Ukraine, Hryvni",
    "UGX": u"Uganda, Shillin",
    "UYU": u"Uruguay, Pesos",
    "UZS": u"Uzbekistan, Sum",
    "VEB": u"Venezuela, Boli",
    "VEF": u"Venez.Bol.Frte",
    "VND": u"Viet Nam, Dong",
    "VUV": u"Vanuatu, Vatu",
    "WST": u"Samoa, Tala",
    "XAF": u"C. Afri., Fra.",
    "XCD": u"E. Car., Dol.",
    "XOF": u"Africa, Francs",
    "XPF": u"Polyn. Francs",
    "YER": u"Yemen, Rials",
    "ZAR": u"S. Afri., Rands",
    "ZMK": u"Zamb., Kwachas",
    "ZWL": u"Zimb., Dollars"
}
