# -*- coding: utf-8 -*-

# 8.8. Países

COUNTRIES = {
    "AD": u"ANDORRA",
    "AE": u"EMIRATOS ARABES UNIDOS",
    "AF": u"AFGANISTAN",
    "AG": u"ANTIGUA Y BARBUDA",
    "AI": u"ANGUILA",
    "AL": u"ALBANIA",
    "AM": u"ARMENIA",
    "AO": u"ANGOLA",
    "AQ": u"ANTARTIDA",
    "AR": u"ARGENTINA",
    "AS": u"SAMOA AMERICANA",
    "AT": u"AUSTRIA",
    "AU": u"AUSTRALIA",
    "AW": u"ARUBA",
    "AX": u"ISLAS \u00c5LAND",
    "AZ": u"AZERBAIYAN",
    "BA": u"BOSNIA Y HERZEGOVINA",
    "BB": u"BARBADOS",
    "BD": u"BANGLADES",
    "BE": u"BELGICA",
    "BF": u"BURKINA FASO",
    "BG": u"BULGARIA",
    "BH": u"BAREIN",
    "BI": u"BURUNDI",
    "BJ": u"BENIN",
    "BL": u"SAN BARTOLOME",
    "BM": u"BERMUDAS",
    "BN": u"BRUNEI DARUSSALAM",
    "BO": u"BOLIVIA, ESTADO PLURINACIONAL DE",
    "BQ": u"BONAIRE, SAN EUSTAQUIO Y SABA",
    "BR": u"BRASIL",
    "BS": u"BAHAMAS",
    "BT": u"BUTAN",
    "BV": u"ISLA BOUVET",
    "BW": u"BOTSUANA",
    "BY": u"BIELORRUSIA",
    "BZ": u"BELICE",
    "CA": u"CANADA",
    "CC": u"ISLAS COCOS (KEELING)",
    "CD": u"CONGO, LA REPUBLICA DEMOCRATICA DEL",
    "CF": u"REPUBLICA CENTROAFRICANA",
    "CG": u"CONGO",
    "CH": u"SUIZA",
    "CI": u"COSTA DE MARFIL",
    "CK": u"ISLAS COOK",
    "CL": u"CHILE",
    "CM": u"CAMERUN",
    "CN": u"CHINA, REPUBLICA POPULAR",
    "CO": u"COLOMBIA",
    "CR": u"COSTA RICA",
    "CU": u"CUBA",
    "CV": u"CABO VERDE",
    "CW": u"CURAZAO",
    "CX": u"ISLA DE NAVIDAD",
    "CY": u"CHIPRE",
    "CZ": u"REPUBLICA CHECA",
    "DE": u"ALEMANIA",
    "DJ": u"YIBUTI",
    "DK": u"DINAMARCA",
    "DM": u"DOMINICA",
    "DO": u"REPUBLICA DOMINICANA",
    "DZ": u"ARGELIA",
    "EC": u"ECUADOR",
    "EE": u"ESTONIA",
    "EG": u"EGIPTO",
    "EH": u"SAHARA OCCIDENTAL",
    "ER": u"ERITREA",
    "ES": u"ESPA\u00d1A",
    "ET": u"ETIOPIA",
    "FI": u"FINLANDIA",
    "FJ": u"FIYI",
    "FK": u"ISLAS FALKLAND (MALVINAS)",
    "FM": u"MICRONESIA, ESTADOS FEDERADOS DE",
    "FO": u"ISLAS FEROE",
    "FR": u"FRANCIA",
    "GA": u"GABON",
    "GB": u"REINO UNIDO",
    "GD": u"GRANADA",
    "GE": u"GEORGIA",
    "GF": u"GUAYANA FRANCESA",
    "GG": u"GUERNSEY",
    "GH": u"GHANA",
    "GI": u"GIBRALTAR",
    "GL": u"GROENLANDIA",
    "GM": u"GAMBIA",
    "GN": u"GUINEA",
    "GP": u"GUADALUPE",
    "GQ": u"GUINEA ECUATORIAL",
    "GR": u"GRECIA",
    "GS": u"ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR",
    "GT": u"GUATEMALA",
    "GU": u"GUAM",
    "GW": u"GUINEA-BISAU",
    "GY": u"GUYANA",
    "HK": u"HONG KONG",
    "HM": u"ISLAS HEARD Y MCDONALD",
    "HN": u"HONDURAS",
    "HR": u"CROACIA",
    "HT": u"HAITI",
    "HU": u"HUNGRIA",
    "ID": u"INDONESIA",
    "IE": u"IRLANDA",
    "IL": u"ISRAEL",
    "IM": u"ISLA DE MAN",
    "IN": u"INDIA",
    "IO": u"TERRITORIO BRITANICO DEL OCEANO",
    "IQ": u"IRAK",
    "IR": u"IRAN, REPUBLICA ISLAMICA DE",
    "IS": u"ISLANDIA",
    "IT": u"ITALIA",
    "JE": u"JERSEY",
    "JM": u"JAMAICA",
    "JO": u"JORDANIA",
    "JP": u"JAPON",
    "KE": u"KENIA",
    "KG": u"KIRGUISTAN",
    "KH": u"CAMBOYA",
    "KI": u"KIRIBATI",
    "KM": u"COMORAS",
    "KN": u"SAN CRISTOBAL Y NIEVES",
    "KP": u"COREA, REPUBLICA DEMOCRATICA POPULAR DE",
    "KR": u"COREA, REPUBLICA DE",
    "KW": u"KUWAIT",
    "KY": u"ISLAS CAIMAN",
    "KZ": u"KAZAJISTAN",
    "LA": u"LAOS REPUBLICA DEMOCRATICA POPULAR LAO",
    "LB": u"LIBANO",
    "LC": u"SANTA LUCIA",
    "LI": u"LIECHTENSTEIN",
    "LK": u"SRI LANKA",
    "LR": u"LIBERIA",
    "LS": u"LESOTO",
    "LT": u"LITUANIA",
    "LU": u"LUXEMBURGO",
    "LV": u"LETONIA",
    "LY": u"LIBIA",
    "MA": u"MARRUECOS",
    "MC": u"MONACO",
    "MD": u"MOLDAVIA, REPUBLICA DE",
    "ME": u"MONTENEGRO",
    "MF": u"SAN MARTIN (PARTE FRANCESA)",
    "MG": u"MADAGASCAR",
    "MH": u"ISLAS MARSHALL",
    "MK": u"MACEDONIA, LA ANTIGUA REPUBLICA YUGOSLAVA DE",
    "ML": u"MALI",
    "MM": u"MYANMAR",
    "MN": u"MONGOLIA",
    "MO": u"MACAO",
    "MP": u"ISLAS MARIANAS DEL NORTE",
    "MQ": u"MARTINICA",
    "MR": u"MAURITANIA",
    "MS": u"MONTSERRAT",
    "MT": u"MALTA",
    "MU": u"MAURICIO",
    "MV": u"MALDIVAS",
    "MW": u"MALAUI",
    "MX": u"MEXICO",
    "MY": u"MALASIA",
    "MZ": u"MOZAMBIQUE",
    "NA": u"NABIMIA",
    "NC": u"NUEVA CALEDONIA",
    "NE": u"NIGER",
    "NF": u"ISLA NORFOLK",
    "NG": u"NIGERIA",
    "NI": u"NICARAGUA",
    "NL": u"PAISES BAJOS",
    "NO": u"NORUEGA",
    "NP": u"NEPAL",
    "NR": u"NAURU",
    "NU": u"NIUE",
    "NZ": u"NUEVA ZELANDA",
    "OM": u"OMAN",
    "PA": u"PANAMA",
    "PE": u"PERU",
    "PF": u"POLINESIA FRANCESA",
    "PG": u"PAPUA NUEVA GUINEA",
    "PH": u"FILIPINAS",
    "PK": u"PAKISTAN",
    "PL": u"POLONIA",
    "PM": u"SAN PEDRO Y MIQUELON",
    "PN": u"PITCAIRN",
    "PR": u"PUERTO RICO",
    "PS": u"PALESTINA, ESTADO DE",
    "PT": u"PORTUGAL",
    "PW": u"PALAOS",
    "PY": u"PARAGUAY",
    "QA": u"QATAR",
    "RE": u"REUNION",
    "RO": u"RUMANIA",
    "RS": u"SERBIA",
    "RU": u"rusia !FEDERACION RUSA",
    "RW": u"RUANDA",
    "SA": u"ARABIA SAUDITA",
    "SB": u"ISLAS SALOMON",
    "SC": u"SEYCHELLES",
    "SD": u"SUDAN",
    "SE": u"SUECIA",
    "SG": u"SINGAPUR",
    "SH": u"SANTA HELENA, ASCENSION Y TRISTAN",
    "SI": u"ESLOVENIA",
    "SJ": u"SVALBARD Y JAN MAYEN",
    "SK": u"ESLOVAQUIA",
    "SL": u"SIERRA LEONA",
    "SM": u"SAN MARINO",
    "SN": u"SENEGAL",
    "SO": u"SOMALIA",
    "SR": u"SURINAM",
    "SS": u"SUDAN DEL SUR",
    "ST": u"SANTO TOME Y PRINCIPE",
    "SV": u"EL SALVADOR",
    "SX": u"SINT MAARTEN (PARTE NEERLANDESA)",
    "SY": u"REPUBLICA ARABE DE SIRIA",
    "SZ": u"SUAZILANDIA",
    "TC": u"ISLAS TURCAS Y CAICOS",
    "TD": u"CHAD",
    "TF": u"TERRITORIOS AUSTRALES FRANCESES",
    "TG": u"TOGO",
    "TH": u"TAILANDIA",
    "TJ": u"TAYIKISTAN",
    "TK": u"TOKELAU",
    "TL": u"TIMOR-LESTE",
    "TM": u"TURKMENISTAN",
    "TN": u"TUNEZ",
    "TO": u"TONGA",
    "TR": u"TURQUIA",
    "TT": u"TRINIDAD Y TOBAGO",
    "TV": u"TUVALU",
    "TW": u"TAIWAN, PROVINCIA DE CHINA",
    "TZ": u"TANZANIA, REPUBLICA UNIDA DE",
    "UA": u"UCRANIA",
    "UG": u"UGANDA",
    "UM": u"ISLAS ULTRAMARINAS MENORES DE ESTADOS UNIDOS",
    "US": u"ESTADOS UNIDOS",
    "UY": u"URUGUAY",
    "UZ": u"UZBEKISTAN",
    "VA": u"Vaticano SANTA SEDE (CIUDAD ESTADO VATICANO)",
    "VC": u"SAN VICENTE Y LAS GRANADINAS",
    "VE": u"VENEZUELA, REPUBLICA BOLIVARIANA DE",
    "VG": u"ISLAS VIRGENES BRITANICAS",
    "VI": u"ISLAS VIRGENES DE LOS ESTADOS UNIDOS",
    "VN": u"VIET NAM",
    "VU": u"VANUATU",
    "WF": u"WALLIS Y FUTUNA",
    "WS": u"SAMOA",
    "YE": u"YEMEN",
    "YT": u"MAYOTTE",
    "ZA": u"SUDAFRICA",
    "ZM": u"ZAMBIA",
    "ZW": u"ZIMBABUE"
}
