# -*- coding: utf-8 -*-

# 8.13. Tipos de Representación

REPRESENTATION_TYPES = {
    "R-00-PN": u"No obligado a registrarse en el RUT PN",
    "R-01-PN": u"Administrador judicial PN",
    "R-02-PN": u"Administrador privado PN",
    "R-03-PN": u"Agente exclusivo de negocios en Colombia PN",
    "R-04-PN": u"Agente oficioso PN",
    "R-05-PN": u"Albacea PN",
    "R-06-PN": u"Apoderado especial PN",
    "R-07-PN": u"Apoderado general PN",
    "R-08-PN": u"Asignatario PN",
    "R-09-PN": u"Comunero PN",
    "R-10-PN": u"Curador PN",
    "R-11-PN": u"Donatario PN",
    "R-12-PN": u"Factor PN",
    "R-14-PN": u"Heredero con administración de bienes PN",
    "R-15-PN": u"Liquidador PN",
    "R-16-PN": u"Mandatario PN",
    "R-17-PN": u"Padre PN",
    "R-21-PN": u"Tutor PN",
    "R-22-PN": u"Representante aduanero PN",
    "R-23-PN": u"Liquidador suplente PN",
    "R-24-PN": u"Depositario Provisional PN",
    "R-25-PN": u"Agente Interventor PN",
    "R-28-PN": u"Heredero designado PN",
    "R-29-PN": u"Persona Natural sin residencia en Colombia con EP PN",
    "R-99-PN": u"Otro tipo de responsable PN",
    "R-01-PJ": u"Administrador judicial PJ",
    "R-02-PJ": u"Administrador privado PJ",
    "R-03-PJ": u"Agente exclusivo de negocios en Colombia PJ",
    "R-06-PJ": u"Apoderado especial PJ",
    "R-07-PJ": u"Apoderado general PJ",
    "R-09-PJ": u"Comunero PJ",
    "R-12-PJ": u"Factor PJ",
    "R-13-PJ": u"Funcionario delegado para cumplir deberes formales PJ",
    "R-15-PJ": u"Liquidador PJ",
    "R-16-PJ": u"Mandatario PJ",
    "R-18-PJ": u"Representante legal principal PJ",
    "R-19-PJ": u"Representante legal suplente PJ",
    "R-20-PJ": u"Síndico PJ",
    "R-22-PJ": u"Representante aduanero PJ",
    "R-23-PJ": u"Liquidador suplente PJ",
    "R-24-PJ": u"Depositario Provisional PJ",
    "R-25-PJ": u"Agente Interventor PJ",
    "R-26-PJ": u"Agente de Aduanas PJ",
    "R-27-PJ": u"Funcionario delegado para cumplir funciones OEA PJ",
    "R-99-PJ": u"Otro tipo de responsable PJ"
}
