# -*- coding: utf-8 -*-

# 8.14. Tipos de Obligaciones-Responsabilidades

LIABILITY_TYPES = {
    "O-01": u"Aporte especial para la administración de justicia",
    "O-02": u"Gravamen a los movimientos financieros",
    "O-03": u"Impuesto al patrimonio",
    "O-04": u"Impuesto sobre la renta y complementario régimen tributario especial",
    "O-05": u"Impuesto sobre la renta y complementario régimen ordinario",
    "O-06": u"Ingresos y patrimonio",
    "O-07": u"Retención en la fuente a título de renta",
    "O-08": u"Retención timbre nacional",
    "O-09": u"Retención en la fuente en el impuesto sobre las ventas",
    "O-10": u"Usuario aduanero",
    "O-11": u"Ventas régimen común",
    "O-12": u"Ventas régimen simplificado",
    "O-13": u"Gran contribuyente",
    "O-14": u"Informante de exógena",
    "O-15": u"Autorretenedor",
    "O-16": u"Obligación de facturar por ingresos de bienes y/o servicios excluidos",
    "O-17": u"Profesionales de compra y venta de divisas",
    "O-18": u"Precios de Transferencia",
    "O-19": u"Productor y/o exportador de bienes exentos",
    "O-20": u"Obtención NIT",
    "O-21": u"Declarar el ingreso o salida del país de divisas o moneda legal colombiana",
    "O-22": u"Obligado a cumplir deberes formales a nombre de terceros",
    "O-23": u"Agente de retención en el impuesto sobre las ventas",
    "O-24": u"Declaración Informativa Consolidada Precios de transferencia",
    "O-26": u"Declaración Informativa Individual Precios de transferencia",
    "O-32": u"Impuesto Nacional a la Gasolina y al ACPM",
    "O-33": u"Impuesto Nacional al consumo",
    "O-34": u"Régimen simplificado impuesto nacional consumo rest y bares",
    "O-35": u"Impuesto sobre la renta para la equidad CREE",
    "O-36": u"Establecimiento Permanente",
    "O-37": u"Obligado a Facturar Electrónicamente Modelo 2242",
    "O-38": u"Facturación Electrónica Voluntaria Modelo 2242",
    "O-39": u"Proveedor de Servicios Tecnológicos PST Modelo 2242",
    "O-40": u"Impuesto a la Riqueza",
    "O-41": u"Declaración anual de activos en el exterior",
    "O-42": u"Obligado a Llevar Contabilidad",
    "O-99": u"Otro tipo de obligado",
    "A-41": u"Beneficiarios de programas especiales de exportación PEX",
    "A-42": u"Depósitos privados para mercancías en tránsito San Andrés",
    "A-43": u"Observadores de las operaciones de importación",
    "A-44": u"Usuarios sistemas especiales Importación exportación",
    "A-46": u"Transportador maritimo régimen de importación y/o exportación",
    "A-47": u"Transportador terrestre régimen de importación y/o exportación",
    "A-48": u"Aeropuerto de servicio publico o privado",
    "A-49": u"Transportador fluvial régimen de importación",
    "A-50": u"Usuario industrial zona franca especial",
    "A-53": u"Agencias de aduanas 1",
    "A-54": u"Usuario Operador Zona Franca Especial",
    "A-55": u"Agencias de aduanas 2",
    "A-56": u"Agencias de aduanas 3",
    "A-57": u"Agencias de aduanas 4",
    "A-58": u"Transportador aéreo nacional",
    "A-60": u"Transportador aéreo, marítimo o fluvial modalidad Cabotaje",
    "A-61": u"Importador de alimentos de consumo humano y animal",
    "A-62": u"Importador Ocasional",
    "A-63": u"Importador de maquinaría y sus partes Decreto 2261 de 2012",
    "A-64": u"Beneficiario Programa de Fomento Industria Automotriz-PROFIA",
    "A-99": u"Otro tipo de agente aduanero"
}
