# -*- coding: utf-8 -*-

# 8.15. Tipos de Usuarios Aduaneros

CUSTOMS_USERS_TYPES = {
    "A-01": u"Agente de carga internacional",
    "A-02": u"Agente marítimo",
    "A-03": u"Almacén general de depósito",
    "A-04": u"Comercializadora internacional(C.I.)",
    "A-05": u"Comerciante de la zona aduanera especial de Inírida, Puerto Carre&ntildeo, Cumaribo y Primavera",
    "A-06": u"Comerciantes de la zona de régimen aduanero especial de Leticia",
    "A-07": u"Comerciantes de la zona de régimen aduanero especial de Maicao, Uribia y Manaure",
    "A-08": u"Comerciantes de la zona de régimen aduanero especial de Urabá, Tumaco y Guapí",
    "A-09": u"Comerciantes del puerto libre de San Andrés, Providencia y Santa Catalina",
    "A-10": u"Depósito público de apoyo logístico internacional",
    "A-11": u"Depósito privado para procesamiento industrial",
    "A-12": u"Depósito privado de transformación o ensamble",
    "A-13": u"Depósito franco",
    "A-14": u"Depósito privado aeronáutico",
    "A-15": u"Depósito privado para distribución internacional",
    "A-16": u"Depósito privado de provisiones de a bordo para consumo y para llevar",
    "A-17": u"Depósito privado para envíos urgentes",
    "A-18": u"Depósito privado",
    "A-19": u"Depósito público",
    "A-20": u"Depósito público para distribución internacional",
    "A-21": u"Exportador de café",
    "A-22": u"Exportador",
    "A-23": u"Importador",
    "A-24": u"Intermediario de tráfico postal y envíos urgentes",
    "A-25": u"Operador de transporte multimodal",
    "A-26": u"Sociedad de intermediación aduanera",
    "A-27": u"Titular de puertos y muelles de servicio público o privado",
    "A-28": u"Transportador aereo régimen de importación y/o exportación",
    "A-29": u"Transportista nacional para operaciones del régimen de tránsito aduanero",
    "A-30": u"Usuario comercial zona franca",
    "A-32": u"Usuario industrial de bienes zona franca",
    "A-34": u"Usuario industrial de servicios zona franca",
    "A-36": u"Usuario operador de zona franca",
    "A-37": u"Usuario aduanero permanente",
    "A-38": u"Usuario altamente exportador",
    "A-39": u"Usuario de zonas económicas especiales de exportación",
    "A-40": u"Deposito privado de instalaciones industriales",
    "A-41": u"Beneficiarios de programas especiales de exportación PEX",
    "A-42": u"Depósitos privados para mercancías en tránsito San Andrés",
    "A-43": u"Observadores de las operaciones de importación",
    "A-44": u"Usuarios sistemas especiales Importación exportación",
    "A-46": u"Transportador maritimo régimen de importación y/o exportación",
    "A-47": u"Transportador terrestre régimen de importación y/o exportación",
    "A-48": u"Aeropuerto de servicio publico o privado",
    "A-49": u"Transportador fluvial régimen de importación",
    "A-50": u"Usuario industrial zona franca especial",
    "A-53": u"Agencias de aduanas 1",
    "A-54": u"Usuario Operador Zona Franca Especial",
    "A-55": u"Agencias de aduanas 2",
    "A-56": u"Agencias de aduanas 3",
    "A-57": u"Agencias de aduanas 4",
    "A-58": u"Transportador aéreo nacional",
    "A-60": u"Transportador aéreo, marítimo o fluvial modalidad Cabotaje",
    "A-61": u"Importador de alimentos de consumo humano y animal",
    "A-62": u"Importador Ocasional",
    "A-63": u"Importador de maquinaría y sus partes Decreto 2261 de 2012",
    "A-64": u"Beneficiario Programa de Fomento Industria Automotriz-PROFIA",
    "A-99": u"Otro tipo de agente aduanero"
}
